name: CI Build

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checkout code and Install dependencies if neccessary
      run: npm install --legacy-peer-deps
    - name: Build app
      run: |
        npm run build


