name: CI Build

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checkout code and Install dependencies if neccessary
      run: npm install --legacy-peer-deps
    - name: Build and Export app
      run: |
        npm run build
        npm run export

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./out
